[build]
  command = "npm install && npm run build"
  functions = "functions"
[[redirects]]
  from = "/scripts"
  to = "/node_modules/paper/dist"
  status = 200
[[redirects]]
  from = "/stylesheets"
  to = "/public/stylesheets"
  status = 200
[[redirects]]
  from = "/javascripts"
  to = "/public/javascripts"
  status = 200
